### PR TITLE
(#175) Fix alerter acknowledgment issue

### LINKED ISSUE #175: Cannot acknowledge alerter
### Platform

Other (provide info in a description)

### Description

All platforms.

Regression introduced in 4879166d4f895a09c5811584dbdb3641a1ab7b21 (#139):

```patch
@@ -90,7 +91,7 @@ namespace godot {
     void TrainSecuritySystem::security_acknowledge(const bool p_enabled) {
         TMoverParameters *mover = get_mover();
         ASSERT_MOVER(mover);
-        if (p_enabled) {
+        if (enabled) {
             mover->SecuritySystem.acknowledge_press();
         } else {
             mover->SecuritySystem.acknowledge_release();
```

Instead of the `p_enabled` argument, the `TrainPart.enabled` option is checked. The emergency button is effectively held down until the vehicle's security system is disabled.

### Reproduction steps

1. Run and move forward SM42 in demo 3d 
2. Wait for the alerter
3. Try to ack by spacebar

### Screenshots and attachments

_No response_

### PR DESCRIPTION
**Pull request by Francjatomarka**
Use p_enabled parameter instead of inherited enabled from TrainPart to ensure correct acknowledgment behavior.

### CODE REVIEW

File: src/systems/TrainSecuritySystem.cpp [hunk 1]
```diff
@@ -88,10 +88,13 @@ namespace godot {
         unregister_command("security_acknowledge", Callable(this, "security_acknowledge"));
     }
 
+
+    // FIXME: 'p_' prefix is intended for pointer parameters,
```
Comment (marcinn) [inline src/systems/TrainSecuritySystem.cpp]: `p_` means `parameter`.

See: https://github.com/MaSzyna-Reloaded/MaSzyna-API-wrapper/blob/4a5bff68ad4bd673e0c582d1a60f7c212ff27e28/CODE_STYLE.md?plain=1#L9

Comment (Francjatomarka) [reply src/systems/TrainSecuritySystem.cpp]: It might come from the projects CODE_STYLE.md, but in some older codebases (like DX9) p_ was often used to mean pointers

```cpp
HRESULT CreateDevice(
  [in]          UINT                  Adapter,
  [in]          D3DDEVTYPE            DeviceType,
  [in]          HWND                  hFocusWindow,
  [in]          DWORD                 BehaviorFlags,
  [in, out]     D3DPRESENT_PARAMETERS *pPresentationParameters,
  [out, retval] IDirect3DDevice9      **ppReturnedDeviceInterface
);
```

Comment (JezSonic) [reply src/systems/TrainSecuritySystem.cpp]: technically, if we switch to prefixing class members, as we probably should, with m_ or something, we can remove the necessity to prefix function params with p_ and use that for pointers

that can be also easily enforced with clang-tidy, so everyone will be forced to follow conventions, or else clang-tidy CI will fail. See [dev/check-naming-convetions](https://github.com/MaSzyna-Reloaded/MaSzyna-API-wrapper/tree/dev/check-naming-convetions)

We should really get on this and enforce persistent naming convention quickly

**Review by JezSonic — APPROVED** [review]

File: src/systems/TrainSecuritySystem.cpp (hunk 1 above)
Comment (marcinn) [reply src/systems/TrainSecuritySystem.cpp]: > It might come from the projects CODE_STYLE.md, but in some older codebases (like DX9) p_ was often used to mean pointers

Since we are creating an add-on for Godot (CPP), we are following the Godot (CPP) conventions.

Comment (marcinn) [reply src/systems/TrainSecuritySystem.cpp]: > if we switch to prefixing class members, as we probably should, with m_ or something, we can remove the necessity to prefix function params with p_ and use that for pointers

I don't see any benefit in importing Microsoft's coding style to Godot (CPP)-based project.

> that can be also easily enforced with clang-tidy, so everyone will be forced to follow conventions [...] We should really get on this and enforce persistent naming convention quickly

Agreed.

**Comment by JezSonic** [comment]
LGTM, works as expected

File: src/systems/TrainSecuritySystem.cpp (hunk 1 above)
Comment (JezSonic) [reply src/systems/TrainSecuritySystem.cpp]: `we are following the Godot (CPP) conventions.`
Then I think We should enable clang-tidy checks to strictly check our code style from `code_style.md` just to ensure unified code

**Comment by marcinn** [comment]
Thanks!
